// Static, immutable reference metadata for the 114 Surahs.
// English/Arabic names sourced from the same open Quran dataset already
// used elsewhere in this project (see arabic_quran.json in the data
// pipeline). Tamil names are NOT duplicated here - they already live in
// public/data/index.json (SurahMeta.name_tamil); fetch that if you need
// them. This module has no dependency on React or the data pipeline and
// never changes at runtime, so it's safe to import from anywhere.

export interface SurahMetadata {
  number: number;
  nameEnglish: string;
  nameArabic: string;
}

export const SURAH_METADATA: SurahMetadata[] = [
  { number: 1, nameEnglish: "Al-Fatihah", nameArabic: "الفاتحة" },
  { number: 2, nameEnglish: "Al-Baqarah", nameArabic: "البقرة" },
  { number: 3, nameEnglish: "Ali 'Imran", nameArabic: "آل عمران" },
  { number: 4, nameEnglish: "An-Nisa", nameArabic: "النساء" },
  { number: 5, nameEnglish: "Al-Ma'idah", nameArabic: "المائدة" },
  { number: 6, nameEnglish: "Al-An'am", nameArabic: "الأنعام" },
  { number: 7, nameEnglish: "Al-A'raf", nameArabic: "الأعراف" },
  { number: 8, nameEnglish: "Al-Anfal", nameArabic: "الأنفال" },
  { number: 9, nameEnglish: "At-Tawbah", nameArabic: "التوبة" },
  { number: 10, nameEnglish: "Yunus", nameArabic: "يونس" },
  { number: 11, nameEnglish: "Hud", nameArabic: "هود" },
  { number: 12, nameEnglish: "Yusuf", nameArabic: "يوسف" },
  { number: 13, nameEnglish: "Ar-Ra'd", nameArabic: "الرعد" },
  { number: 14, nameEnglish: "Ibrahim", nameArabic: "ابراهيم" },
  { number: 15, nameEnglish: "Al-Hijr", nameArabic: "الحجر" },
  { number: 16, nameEnglish: "An-Nahl", nameArabic: "النحل" },
  { number: 17, nameEnglish: "Al-Isra", nameArabic: "الإسراء" },
  { number: 18, nameEnglish: "Al-Kahf", nameArabic: "الكهف" },
  { number: 19, nameEnglish: "Maryam", nameArabic: "مريم" },
  { number: 20, nameEnglish: "Taha", nameArabic: "طه" },
  { number: 21, nameEnglish: "Al-Anbya", nameArabic: "الأنبياء" },
  { number: 22, nameEnglish: "Al-Hajj", nameArabic: "الحج" },
  { number: 23, nameEnglish: "Al-Mu'minun", nameArabic: "المؤمنون" },
  { number: 24, nameEnglish: "An-Nur", nameArabic: "النور" },
  { number: 25, nameEnglish: "Al-Furqan", nameArabic: "الفرقان" },
  { number: 26, nameEnglish: "Ash-Shu'ara", nameArabic: "الشعراء" },
  { number: 27, nameEnglish: "An-Naml", nameArabic: "النمل" },
  { number: 28, nameEnglish: "Al-Qasas", nameArabic: "القصص" },
  { number: 29, nameEnglish: "Al-'Ankabut", nameArabic: "العنكبوت" },
  { number: 30, nameEnglish: "Ar-Rum", nameArabic: "الروم" },
  { number: 31, nameEnglish: "Luqman", nameArabic: "لقمان" },
  { number: 32, nameEnglish: "As-Sajdah", nameArabic: "السجدة" },
  { number: 33, nameEnglish: "Al-Ahzab", nameArabic: "الأحزاب" },
  { number: 34, nameEnglish: "Saba", nameArabic: "سبإ" },
  { number: 35, nameEnglish: "Fatir", nameArabic: "فاطر" },
  { number: 36, nameEnglish: "Ya-Sin", nameArabic: "يس" },
  { number: 37, nameEnglish: "As-Saffat", nameArabic: "الصافات" },
  { number: 38, nameEnglish: "Sad", nameArabic: "ص" },
  { number: 39, nameEnglish: "Az-Zumar", nameArabic: "الزمر" },
  { number: 40, nameEnglish: "Ghafir", nameArabic: "غافر" },
  { number: 41, nameEnglish: "Fussilat", nameArabic: "فصلت" },
  { number: 42, nameEnglish: "Ash-Shuraa", nameArabic: "الشورى" },
  { number: 43, nameEnglish: "Az-Zukhruf", nameArabic: "الزخرف" },
  { number: 44, nameEnglish: "Ad-Dukhan", nameArabic: "الدخان" },
  { number: 45, nameEnglish: "Al-Jathiyah", nameArabic: "الجاثية" },
  { number: 46, nameEnglish: "Al-Ahqaf", nameArabic: "الأحقاف" },
  { number: 47, nameEnglish: "Muhammad", nameArabic: "محمد" },
  { number: 48, nameEnglish: "Al-Fath", nameArabic: "الفتح" },
  { number: 49, nameEnglish: "Al-Hujurat", nameArabic: "الحجرات" },
  { number: 50, nameEnglish: "Qaf", nameArabic: "ق" },
  { number: 51, nameEnglish: "Adh-Dhariyat", nameArabic: "الذاريات" },
  { number: 52, nameEnglish: "At-Tur", nameArabic: "الطور" },
  { number: 53, nameEnglish: "An-Najm", nameArabic: "النجم" },
  { number: 54, nameEnglish: "Al-Qamar", nameArabic: "القمر" },
  { number: 55, nameEnglish: "Ar-Rahman", nameArabic: "الرحمن" },
  { number: 56, nameEnglish: "Al-Waqi'ah", nameArabic: "الواقعة" },
  { number: 57, nameEnglish: "Al-Hadid", nameArabic: "الحديد" },
  { number: 58, nameEnglish: "Al-Mujadila", nameArabic: "المجادلة" },
  { number: 59, nameEnglish: "Al-Hashr", nameArabic: "الحشر" },
  { number: 60, nameEnglish: "Al-Mumtahanah", nameArabic: "الممتحنة" },
  { number: 61, nameEnglish: "As-Saf", nameArabic: "الصف" },
  { number: 62, nameEnglish: "Al-Jumu'ah", nameArabic: "الجمعة" },
  { number: 63, nameEnglish: "Al-Munafiqun", nameArabic: "المنافقون" },
  { number: 64, nameEnglish: "At-Taghabun", nameArabic: "التغابن" },
  { number: 65, nameEnglish: "At-Talaq", nameArabic: "الطلاق" },
  { number: 66, nameEnglish: "At-Tahrim", nameArabic: "التحريم" },
  { number: 67, nameEnglish: "Al-Mulk", nameArabic: "الملك" },
  { number: 68, nameEnglish: "Al-Qalam", nameArabic: "القلم" },
  { number: 69, nameEnglish: "Al-Haqqah", nameArabic: "الحاقة" },
  { number: 70, nameEnglish: "Al-Ma'arij", nameArabic: "المعارج" },
  { number: 71, nameEnglish: "Nuh", nameArabic: "نوح" },
  { number: 72, nameEnglish: "Al-Jinn", nameArabic: "الجن" },
  { number: 73, nameEnglish: "Al-Muzzammil", nameArabic: "المزمل" },
  { number: 74, nameEnglish: "Al-Muddaththir", nameArabic: "المدثر" },
  { number: 75, nameEnglish: "Al-Qiyamah", nameArabic: "القيامة" },
  { number: 76, nameEnglish: "Al-Insan", nameArabic: "الانسان" },
  { number: 77, nameEnglish: "Al-Mursalat", nameArabic: "المرسلات" },
  { number: 78, nameEnglish: "An-Naba", nameArabic: "النبإ" },
  { number: 79, nameEnglish: "An-Nazi'at", nameArabic: "النازعات" },
  { number: 80, nameEnglish: "'Abasa", nameArabic: "عبس" },
  { number: 81, nameEnglish: "At-Takwir", nameArabic: "التكوير" },
  { number: 82, nameEnglish: "Al-Infitar", nameArabic: "الإنفطار" },
  { number: 83, nameEnglish: "Al-Mutaffifin", nameArabic: "المطففين" },
  { number: 84, nameEnglish: "Al-Inshiqaq", nameArabic: "الإنشقاق" },
  { number: 85, nameEnglish: "Al-Buruj", nameArabic: "البروج" },
  { number: 86, nameEnglish: "At-Tariq", nameArabic: "الطارق" },
  { number: 87, nameEnglish: "Al-A'la", nameArabic: "الأعلى" },
  { number: 88, nameEnglish: "Al-Ghashiyah", nameArabic: "الغاشية" },
  { number: 89, nameEnglish: "Al-Fajr", nameArabic: "الفجر" },
  { number: 90, nameEnglish: "Al-Balad", nameArabic: "البلد" },
  { number: 91, nameEnglish: "Ash-Shams", nameArabic: "الشمس" },
  { number: 92, nameEnglish: "Al-Layl", nameArabic: "الليل" },
  { number: 93, nameEnglish: "Ad-Duhaa", nameArabic: "الضحى" },
  { number: 94, nameEnglish: "Ash-Sharh", nameArabic: "الشرح" },
  { number: 95, nameEnglish: "At-Tin", nameArabic: "التين" },
  { number: 96, nameEnglish: "Al-'Alaq", nameArabic: "العلق" },
  { number: 97, nameEnglish: "Al-Qadr", nameArabic: "القدر" },
  { number: 98, nameEnglish: "Al-Bayyinah", nameArabic: "البينة" },
  { number: 99, nameEnglish: "Az-Zalzalah", nameArabic: "الزلزلة" },
  { number: 100, nameEnglish: "Al-'Adiyat", nameArabic: "العاديات" },
  { number: 101, nameEnglish: "Al-Qari'ah", nameArabic: "القارعة" },
  { number: 102, nameEnglish: "At-Takathur", nameArabic: "التكاثر" },
  { number: 103, nameEnglish: "Al-'Asr", nameArabic: "العصر" },
  { number: 104, nameEnglish: "Al-Humazah", nameArabic: "الهمزة" },
  { number: 105, nameEnglish: "Al-Fil", nameArabic: "الفيل" },
  { number: 106, nameEnglish: "Quraysh", nameArabic: "قريش" },
  { number: 107, nameEnglish: "Al-Ma'un", nameArabic: "الماعون" },
  { number: 108, nameEnglish: "Al-Kawthar", nameArabic: "الكوثر" },
  { number: 109, nameEnglish: "Al-Kafirun", nameArabic: "الكافرون" },
  { number: 110, nameEnglish: "An-Nasr", nameArabic: "النصر" },
  { number: 111, nameEnglish: "Al-Masad", nameArabic: "المسد" },
  { number: 112, nameEnglish: "Al-Ikhlas", nameArabic: "الإخلاص" },
  { number: 113, nameEnglish: "Al-Falaq", nameArabic: "الفلق" },
  { number: 114, nameEnglish: "An-Nas", nameArabic: "الناس" },
];
